version: "3"
services:
  # hub:
  #   image: selenium/hub:latest
  #   ports:
  #     - "4444:4444"
  # chrome:
  #   image: selenium/node-chrome
  #   depends_on:
  #     - hub
  #   environment:
  #     - HUB_HOST=hub
  pytest_demo:
    image: docker_pytest_demo
    # depends_on:
    #   - chrome
    volumes:
      - ./output/reports:/tmp/reports
    command: pytest -v --html=reports/test_sample_report.html

  # test_pdemo1:
  #   image: docker_pytest
  #   # volumes:
  #   #   - ./output/result:/user/share/test-output
  #   command: pytest -v -m demo1 --html=reports/test_sample_report.html